
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/full_view
    username: postgres
    password: 1234qwer!QAZ
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none